Metrics/AbcSize:
  Max: 18

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Metrics/LineLength:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/schema.rb'
  Max: 90

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
