Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'db/schema.rb'
    - 'config/initializers/*'
    - 'config/routes.rb'

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 13
  Exclude:
    - 'db/migrate/*.rb'

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Metrics/LineLength:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*.rb'
    - 'app/dashboards/*.rb'
  Max: 90

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
